### PR TITLE
Fix CMake config for building examples with Boost

### PR DESCRIPTION
**Pull request by saibalde**
When trying to compile the library with Boost support, I encountered an error. The compiler could not find header `<boost/random/linear_congruential.hpp>` when building the `time` executable in `examples`.

To fix this, I modified the `examples` CMake configuration and linked the executable against the header-only Boost target. This will ensure the compiler finds the headers, even when they are installed in non-standard locations.

### CODE REVIEW

**Comment by rabauke** [comment]
If your compiler complains only about the missing (not found) header file `<boost/random/linear_congruential.hpp>` then adding `target_link_libraries` to `CMakeLists.txt` is probably not the right way to fix this issue, even if it fixes the issue exidently. Linking and header files are two unrelated things.

Can you give a detailed error message that is emitted without your fix and detail your system configuration (Compiler, OS, Boost installation)?

**Comment by saibalde** [comment]
I'm using the target feature new in CMake 3.x.x. From the [FindBoost.cmake documentation](https://cmake.org/cmake/help/v3.10/module/FindBoost.html), `Boost::boost` is an imported header-only target - it won't link any of the Boost libraries. We can use the older `include_directories` as well.

### Specs

I'm using MacOS Catalina with Homebrew GCC 9.2.0; OpenMPI 3.1.5 and Boost 1.70.0 were installed via [spack](https://spack.readthedocs.io/en/latest/) with following specs:
```
openmpi@3.1.5%gcc@9.2.0~cuda+cxx_exceptions fabrics=none ~java~legacylaunchers~memchecker~pmi schedulers=none ~sqlite3~thread_multiple+vt arch=darwin-catalina-broadwell
    ^hwloc@1.11.11%gcc@9.2.0~cairo~cuda~gl+libxml2~nvml~pci+shared arch=darwin-catalina-broadwell
        ^libxml2@2.9.9%gcc@9.2.0~python arch=darwin-catalina-broadwell
            ^libiconv@1.16%gcc@9.2.0 arch=darwin-catalina-broadwell
            ^pkgconf@1.6.3%gcc@9.2.0 arch=darwin-catalina-broadwell
            ^xz@5.2.4%gcc@9.2.0 arch=darwin-catalina-broadwell
            ^zlib@1.2.11%gcc@9.2.0+optimize+pic+shared arch=darwin-catalina-broadwell
boost@1.70.0%gcc@9.2.0+atomic+chrono~clanglibcpp~context~coroutine cxxstd=98 +date_time~debug+exception~fiber+filesystem+graph~icu+iostreams+locale+log+math~mpi+multithreaded~numpy~pic+program_options~python+random+regex+serialization+shared+signals~singlethreaded+system~taggedlayout+test+thread+timer~versionedlayout visibility=hidden +wave arch=darwin-catalina-broadwell
    ^bzip2@1.0.8%gcc@9.2.0+shared arch=darwin-catalina-broadwell
        ^diffutils@3.7%gcc@9.2.0 arch=darwin-catalina-broadwell
            ^libiconv@1.16%gcc@9.2.0 arch=darwin-catalina-broadwell
    ^zlib@1.2.11%gcc@9.2.0+optimize+pic+shared arch=darwin-catalina-broadwell
```

### Build Logs

CMake Configuration
```
-- The C compiler identification is GNU 9.2.0
-- The CXX compiler identification is GNU 9.2.0
-- Checking whether C compiler has -isysroot
-- Checking whether C compiler has -isysroot - yes
-- Checking whether C compiler supports OSX deployment target flag
-- Checking whether C compiler supports OSX deployment target flag - yes
-- Check for working C compiler: /usr/local/bin/gcc-9
-- Check for working C compiler: /usr/local/bin/gcc-9 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Checking whether CXX compiler has -isysroot
-- Checking whether CXX compiler has -isysroot - yes
-- Checking whether CXX compiler supports OSX deployment target flag
-- Checking whether CXX compiler supports OSX deployment target flag - yes
-- Check for working CXX compiler: /usr/local/bin/g++-9
-- Check for working CXX compiler: /usr/local/bin/g++-9 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Boost: /Users/saibal/spack/opt/spack/darwin-catalina-broadwell/gcc-9.2.0/boost-1.70.0-2doyo2zaz7imtulan54hhcc6uf2ppzob/include (found version "1.70.0")
-- Found MPI_C: /Users/saibal/spack/opt/spack/darwin-catalina-broadwell/gcc-9.2.0/openmpi-3.1.5-anxtl2qrkx5tjbsj4vlwwqtctrkwwar6/lib/libmpi.dylib (found version "3.1")
-- Found MPI_CXX: /Users/saibal/spack/opt/spack/darwin-catalina-broadwell/gcc-9.2.0/openmpi-3.1.5-anxtl2qrkx5tjbsj4vlwwqtctrkwwar6/lib/libmpi_cxx.dylib (found version "3.1")
-- Found MPI: TRUE (found version "3.1")
-- Found OpenMP_C: -fopenmp (found version "4.5")
-- Found OpenMP_CXX: -fopenmp (found version "4.5")
-- Found OpenMP: TRUE (found version "4.5")
-- Could NOT find TBB (missing: TBB_INCLUDE_DIRS TBB_LIBRARIES)
-- Found Boost: /Users/saibal/spack/opt/spack/darwin-catalina-broadwell/gcc-9.2.0/boost-1.70.0-2doyo2zaz7imtulan54hhcc6uf2ppzob/include (found version "1.70.0") found components: unit_test_framework
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/saibal/codes/trng4/build
```
Make output
```
[  1%] Building CXX object trng/CMakeFiles/trng4_shared.dir/mrg4.cc.o
[  2%] Building CXX object trng/CMakeFiles/trng4_shared.dir/mrg5.cc.o
[  4%] Building CXX object trng/CMakeFiles/trng4_shared.dir/mrg5s.cc.o
[  5%] Building CXX object trng/CMakeFiles/trng4_shared.dir/mt19937_64.cc.o
[  6%] Building CXX object trng/CMakeFiles/trng4_shared.dir/mt19937.cc.o
[  8%] Building CXX object trng/CMakeFiles/trng4_shared.dir/yarn2.cc.o
[  9%] Building CXX object trng/CMakeFiles/trng4_shared.dir/yarn3.cc.o
[ 10%] Building CXX object trng/CMakeFiles/trng4_shared.dir/yarn3s.cc.o
[ 12%] Building CXX object trng/CMakeFiles/trng4_shared.dir/yarn4.cc.o
[ 13%] Building CXX object trng/CMakeFiles/trng4_shared.dir/yarn5.cc.o
[ 15%] Building CXX object trng/CMakeFiles/trng4_shared.dir/yarn5s.cc.o
[ 16%] Linking CXX shared library libtrng4.dylib
[ 24%] Built target trng4_shared
[ 26%] Building CXX object trng/CMakeFiles/trng4_static.dir/mrg4.cc.o
[ 27%] Building CXX object trng/CMakeFiles/trng4_static.dir/mrg5.cc.o
[ 28%] Building CXX object trng/CMakeFiles/trng4_static.dir/mrg5s.cc.o
[ 30%] Building CXX object trng/CMakeFiles/trng4_static.dir/mt19937_64.cc.o
[ 31%] Building CXX object trng/CMakeFiles/trng4_static.dir/mt19937.cc.o
[ 32%] Building CXX object trng/CMakeFiles/trng4_static.dir/yarn2.cc.o
[ 34%] Building CXX object trng/CMakeFiles/trng4_static.dir/yarn3.cc.o
[ 35%] Building CXX object trng/CMakeFiles/trng4_static.dir/yarn3s.cc.o
[ 36%] Building CXX object trng/CMakeFiles/trng4_static.dir/yarn4.cc.o
[ 38%] Building CXX object trng/CMakeFiles/trng4_static.dir/yarn5.cc.o
[ 39%] Building CXX object trng/CMakeFiles/trng4_static.dir/yarn5s.cc.o
[ 41%] Linking CXX static library libtrng4.a
[ 49%] Built target trng4_static
[ 50%] Linking CXX executable bernoulli_dist
[ 52%] Built target bernoulli_dist
[ 53%] Linking CXX executable correlated_normal_dist
[ 54%] Built target correlated_normal_dist
Scanning dependencies of target pi_block_mpi
[ 56%] Building CXX object examples/CMakeFiles/pi_block_mpi.dir/pi_block_mpi.cc.o
[ 57%] Linking CXX executable pi_block_mpi
[ 57%] Built target pi_block_mpi
Scanning dependencies of target cpp11
[ 58%] Building CXX object examples/CMakeFiles/cpp11.dir/cpp11.cc.o
[ 60%] Linking CXX executable cpp11
[ 60%] Built target cpp11
Scanning dependencies of target Ising_model
[ 61%] Building CXX object examples/CMakeFiles/Ising_model.dir/Ising_model.cc.o
[ 63%] Linking CXX executable Ising_model
[ 63%] Built target Ising_model
Scanning dependencies of target stl_container
[ 64%] Building CXX object examples/CMakeFiles/stl_container.dir/stl_container.cc.o
[ 65%] Linking CXX executable stl_container
[ 65%] Built target stl_container
Scanning dependencies of target pi_leap_openmp
[ 67%] Building CXX object examples/CMakeFiles/pi_leap_openmp.dir/pi_leap_openmp.cc.o
[ 68%] Linking CXX executable pi_leap_openmp
[ 68%] Built target pi_leap_openmp
Scanning dependencies of target discrete_dist
[ 69%] Building CXX object examples/CMakeFiles/discrete_dist.dir/discrete_dist.cc.o
[ 71%] Linking CXX executable discrete_dist
[ 71%] Built target discrete_dist
Scanning dependencies of target pi_leap_mpi
[ 72%] Building CXX object examples/CMakeFiles/pi_leap_mpi.dir/pi_leap_mpi.cc.o
[ 73%] Linking CXX executable pi_leap_mpi
[ 73%] Built target pi_leap_mpi
Scanning dependencies of target discrete_dist_c_style
[ 75%] Building CXX object examples/CMakeFiles/discrete_dist_c_style.dir/discrete_dist_c_style.cc.o
[ 76%] Linking CXX executable discrete_dist_c_style
[ 76%] Built target discrete_dist_c_style
Scanning dependencies of target sample_output
[ 78%] Building CXX object examples/CMakeFiles/sample_output.dir/sample_output.cc.o
[ 79%] Linking CXX executable sample_output
[ 79%] Built target sample_output
Scanning dependencies of target pi_block_openmp
[ 80%] Building CXX object examples/CMakeFiles/pi_block_openmp.dir/pi_block_openmp.cc.o
[ 82%] Linking CXX executable pi_block_openmp
[ 82%] Built target pi_block_openmp
Scanning dependencies of target pi
[ 83%] Building CXX object examples/CMakeFiles/pi.dir/pi.cc.o
[ 84%] Linking CXX executable pi
[ 84%] Built target pi
Scanning dependencies of target time
[ 86%] Building CXX object examples/CMakeFiles/time.dir/time.cc.o
/Users/saibal/codes/trng4/examples/time.cc:63:10: fatal error: boost/random/linear_congruential.hpp: No such file or directory
   63 | #include <boost/random/linear_congruential.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [examples/CMakeFiles/time.dir/time.cc.o] Error 1
make[1]: *** [examples/CMakeFiles/time.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by rabauke** [comment]
> I'm using the target feature new in CMake 3.x.x. From the [FindBoost.cmake documentation](https://cmake.org/cmake/help/v3.10/module/FindBoost.html), `Boost::boost` is an imported header-only target - it won't link any of the Boost libraries.

I understand. Are you able to compile the unit tests in `tests` or is a similar patch required for `tests/CMakeLists.txt`, too?

**Comment by saibalde** [comment]
The unit tests compile without any modification because of the `include_directories(${Boost_INCLUDE_DIRS})` in the `tests/CMakeLists.txt`.

**Pull request merged**
